###Create complaint with user id
POST http://localhost:3000/complaint
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlYmFhNzk3M2JmMTMwOGU5M2ZjYSIsImVtYWlsIjoidXNlcjNAZ21haWwuY29tIiwiaWF0IjoxNjY5NzIxNzQ3LCJleHAiOjE2Njk3MjUzNDd9.AAfA6KcZa6CNxJSUbKk6JwY4_ekXp7oP-58zH4borZk
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4MTBkZjEyZWI3Y2MyMWNlNTNhYTQxIiwiaWF0IjoxNjY5NzA5MjIyLCJleHAiOjE2Njk3MTI4MjJ9.93jTgWN7g5FUPM3r1jy8SM3Dt_-qqOWeRArkPBWkObQ

{
    "title":"test",
    "body":"test",
    "user":"6380ebaa7973bf1308e93fca"
}

###Get complaint by user id
GET http://localhost:3000/complaint/6385f58c581a423e4bae573f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI5QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1OGM1ODFhNDIzZTRiYWU1NzNmIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MDA0NjMyOCwiZXhwIjoxNjcwMDQ5OTI4fQ.sP280G2v9wtdzA8Rzy8SxKcDHQt14iS4iPSVy1MDkgc
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1ZGI1ODFhNDIzZTRiYWU1NzRiIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcwMDQ2MzAyLCJleHAiOjE2NzAwNDk5MDJ9.pF9IthcmoHzFjW1xJTcNhbG9Y-w8ZHTCOiTGIXoJuRw



###Update status
PATCH http://localhost:3000/complaint/6385f5c3581a423e4bae5748/comp/6385fe154db404436926abad
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI5QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1OGM1ODFhNDIzZTRiYWU1NzNmIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MDA0NjMyOCwiZXhwIjoxNjcwMDQ5OTI4fQ.sP280G2v9wtdzA8Rzy8SxKcDHQt14iS4iPSVy1MDkgc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1ZGI1ODFhNDIzZTRiYWU1NzRiIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcwMDQ2MzAyLCJleHAiOjE2NzAwNDk5MDJ9.pF9IthcmoHzFjW1xJTcNhbG9Y-w8ZHTCOiTGIXoJuRw

{
    "status":"rejected"
}

###View all complaint
GET http://localhost:3000/complaint?status=pending
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI5QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1OGM1ODFhNDIzZTRiYWU1NzNmIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MDA0NjMyOCwiZXhwIjoxNjcwMDQ5OTI4fQ.sP280G2v9wtdzA8Rzy8SxKcDHQt14iS4iPSVy1MDkgc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1ZGI1ODFhNDIzZTRiYWU1NzRiIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjcwMDQ2MzAyLCJleHAiOjE2NzAwNDk5MDJ9.pF9IthcmoHzFjW1xJTcNhbG9Y-w8ZHTCOiTGIXoJuRw