###Create complaint with user id
POST http://localhost:3000/complaint
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlYmFhNzk3M2JmMTMwOGU5M2ZjYSIsImVtYWlsIjoidXNlcjNAZ21haWwuY29tIiwiaWF0IjoxNjY5NzIxNzQ3LCJleHAiOjE2Njk3MjUzNDd9.AAfA6KcZa6CNxJSUbKk6JwY4_ekXp7oP-58zH4borZk
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4MTBkZjEyZWI3Y2MyMWNlNTNhYTQxIiwiaWF0IjoxNjY5NzA5MjIyLCJleHAiOjE2Njk3MTI4MjJ9.93jTgWN7g5FUPM3r1jy8SM3Dt_-qqOWeRArkPBWkObQ

{
    "title":"test",
    "body":"test",
    "user":"6380ebaa7973bf1308e93fca"
}

###Get complaint by user id
GET http://localhost:3000/complaint/6380ebaa7973bf1308e93fca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODBlYmFhNzk3M2JmMTMwOGU5M2ZjYSIsImVtYWlsIjoidXNlcjNAZ21haWwuY29tIiwiaWF0IjoxNjY5NzIxNzQ3LCJleHAiOjE2Njk3MjUzNDd9.AAfA6KcZa6CNxJSUbKk6JwY4_ekXp7oP-58zH4borZk
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4MTBkZjEyZWI3Y2MyMWNlNTNhYTQxIiwiaXNBZG1pbiI6ImFkbWluIiwiaWF0IjoxNjY5NzIwMTU4LCJleHAiOjE2Njk3MjM3NTh9.GoZ2ClXbl0Wh7s23TVjzEpWGRWrb2ZfKmlurrm-DoZM


###Update status
PATCH http://localhost:3000/complaint/6380ebaa7973bf1308e93fca/comp/638107193ec8d68d23fbd88d
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlkIjoiNjM4MGViYWE3OTczYmYxMzA4ZTkzZmNhIiwiaXNBZG1pbiI6ImNsaWVudCIsImlhdCI6MTY2OTcyMDExMiwiZXhwIjoxNjY5NzIzNzEyfQ.i7Vawm08xiepaxPv1_UmabZU131OJiZm4wcEKIIsGs4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODEwZGYxMmViN2NjMjFjZTUzYWE0MSIsImVtYWlsIjoidXNlcjRAZ21haWwuY29tIiwiaWF0IjoxNjY5NzIyNTcyLCJleHAiOjE2Njk3MjYxNzJ9.Q3TjniSKM4a0bVrzXdwC_QwuBQegS4pL-wdzzDaM6GU

{
    "status":"resolved"
}

###View all complaint
GET http://localhost:3000/complaint?status=resolved
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsImlkIjoiNjM4MGViYWE3OTczYmYxMzA4ZTkzZmNhIiwiaXNBZG1pbiI6ImNsaWVudCIsImlhdCI6MTY2OTcyMDExMiwiZXhwIjoxNjY5NzIzNzEyfQ.i7Vawm08xiepaxPv1_UmabZU131OJiZm4wcEKIIsGs4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI0QGdtYWlsLmNvbSIsImlkIjoiNjM4NWY1ZGI1ODFhNDIzZTRiYWU1NzRiIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjY5ODIzMjQwLCJleHAiOjE2Njk4MjY4NDB9.oKbM05mhIvxV6XlJI9-ZIurhAivFMTVZPHLnwgberRc